version: '3.7'

networks:
   backend:
    name: backend

services:
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
      - /client/dist
    ports:
      - "80:5000"

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./server/api
    depends_on: 
      - db
    volumes:
      - ./server/api:/api
      - /api/node_modules
    ports:
      - "4200:4200"
    networks:
      - backend

  socket:
    container_name: socket
    restart: unless-stopped 
    build:
      context: ./server/socket
    volumes:
      - ./server/socket:/socket
      - /socket/node_modules
    ports:
      - "3000:3000"
 
  db: 
    image: mongo:4.0
    container_name: db
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    networks:
      - backend
