version: '3.7'
services:
  vue-client:
     image: client
     command: serve -s dist
     ports:
       - "80:5000"

  node-server:
    image: api
    restart: always
    ports:
      - "4200:4200"

  socket-io-server:
    image: socket
    restart: always
    ports:
      - "3000:3000"
  
  mongodb_container: 
    image: mongo:latest
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"