version: '3.7'

networks:
   backend:
    name: backend

services:
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
    ports:
      - "80:5000"

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./server/api_sql
    command: sh -c 'echo "running migration..."; cd /api ; yarn migrate; yarn serve'
    depends_on: 
      - db
    ports:
      - "4200:4200"
    networks:
      - backend

  socket:
    container_name: socket
    restart: unless-stopped 
    build:
      context: ./server/socket
    ports:
      - "3000:3000"

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=lyrics_projection
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    networks:
      - backend
