version: '3.7'
services:
  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
      - /client/dist
    ports:
      - "80:5000"

  api:
    container_name: api
    build:
      context: ./server/api
    depends_on: 
      - db
    volumes:
      - ./server/api:/api
      - /api/node_modules
    ports:
      - "4200:4200"
    restart: always

  socket:
    container_name: socket
    build:
      context: ./server/socket
    volumes:
      - ./server/socket:/socket
      - /socket/node_modules
    ports:
      - "3000:3000"
    restart: always
  
  db: 
    image: mongo:latest
    container_name: db
    restart: always